version: "3.2"
services:
  database:
    container_name: mongodb
    image: mongo:6-jammy
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_DATABASE=test
    networks:
      - backend
    volumes:
      - db-crypto-satangpro:/data/db

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - backend
    restart: unless-stopped

  cronjob-service:
    container_name: cronjob-service
    image: crypto-satangpro
    build: .
    environment:
      - MODE=job
      - ETH_JSON_RPC_API_URL=https://mainnet.infura.io/v3/dfd1ca1cd6f8406cb25904c114609987
      - RABBIT_MQ_URL=amqp://guest:guest@rabbitmq:5672/
    networks:
      - backend
    restart: unless-stopped

  record-service:
    container_name: record-service
    image: crypto-satangpro
    build: .
    environment:
      - MODE=record
      - RABBIT_MQ_URL=amqp://guest:guest@rabbitmq:5672/
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/admin
      - DATABASE_NAME=admin
      - ADDRESS_MONITOR=0x28c6c06298d514db089934071355e5743bf21d60
      - LINE_NOTIFY_TOKEN=Zo7eKnA2i2Zp1YQ8Ev07dIqBeSayWxvkiDlj0UewekL
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
    driver: bridge

volumes:
  db-crypto-satangpro: